# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "scotch/box"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.hostname = "scotchbox"
	config.vm.provision :shell, :path => "provision.sh"
	
	# for sinatra
	config.vm.synced_folder "./app", "/home/vagrant/src", :mount_options => ["dmode=777", "fmode=666"]
	config.vm.network "forwarded_port", guest: 4567, host:4567
end
