dbserver:
  build: ./mysql
  ports:
    - 3306:3306
  hostname: dbserver
  environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: ""
app:
  build: ./
  ports:
    - 8080:8080
  links:
    - dbserver
  volumes:
    - $PWD:/home
  tty: true



