
sh/ruby:
	docker run -it --volumes-from mysql_data --link mysql -v /Users/glacier/Dropbox/dev/src/github.com/g-hyoga/tutorials/docker-ruby:/home g-hyoga/docker-ruby:latest bash

sh/mysql:
	docker run -it --volumes-from mysql_data --name mysql mysql bash


