version: '3'
services:
  db:
    image: mysql:5.7 
    volumes:
      - "data:/var/lib/mysql"
      - "data:/var/log/mysql"
      - "./mysql:/etc/mysql/conf.d"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  data:

 
